### ISSUE TITLE
amendListener ?

### ISSUE THREAD

**Issue by srilq** [choojs/nanobus#18]
Why no amendListener?

The specific usage for this is ensuring an event runs after Choo RENDER on PUSHSTATE:
emitter.amendListener(PUSHSTATE, {doAfterRender})

There’s probably a good reason not to
do this, or maybe .on already works this way and I’m misunderstanding something. I’m curious!

**Comment by yoshuawuyts** [comment]
So far we've only based it on the Node API - it seems farily complete, and
straight forward to learn. The only difference is that we support the `*`
event. Hope this makes sense!

**Comment by srilq** [comment]
@yoshuawuyts  Yep, thanks!

I think I’ve found a possible solution to this problem..! 😬😕

```js
emitter.prependListener(state.events.PUSHSTATE, function () {
  emitter.once(state.events.RENDER, function () {
    // ...
  })
})
```
