### ISSUE TITLE
Allow symbols for event keys

### ISSUE THREAD

**Issue by lordvlad** [choojs/nanobus#35]
My idea is to pass available events between modules. Right now I'm doing

store module
```js
const addMessage = 'addMessage'
export const events = { addMessage }
export const store = (state, emitter) {
  emitter.on(addMessage, () => { ... })
}
```

view module
```js
import { events } from './module.mjs'
export const view = (state, emit) => html`
   <button onclick=${() => emit(events.addMessage)}>click me </button>`
```

But I really want to make use of symbols (really not sure why) so that I can write instead in my store module

```js
const addMessage = Symbol('addMessage')
```

This would only require a change to a couple of assertions, so that

```js
assert.equal(typeof eventName, 'string', 'nanobus.removeListener: eventName should be type string')
```
reads

```js
const allowedKeyTypes = ['string', 'symbol']
assert.ok(allowedKeyTypes.includes(typeof eventName), 'nanobus.removeListener: eventName should be type string')
```
I'd be happy to create a pull request if that is something you'd accept.

Cheers!

**Comment by goto-bus-stop** [comment]
`typeof name === 'string' || typeof name === 'symbol'` would be good I think. `.includes` isn't supported everywhere
