### ISSUE TITLE
removeListener crashing: "splice is not a function" from remove-array-items

### ISSUE THREAD

**Issue by BlooJeans** [choojs/nanobus#37]
nanobus depends on `"remove-array-items": "^1.0.0"`, which previously resolved to `1.0.0`.  As of 27 days ago, it now resolves to `1.1.0`, which is when they changed how the function was exported, causing the splice function to not be the actual thing exported, but instead `{ default: Function }`

App developers:
To fix the issue in your app, you might be able to force it to use version 1.0.0 by adding
`"remove-array-items": "1.0.0"` to your apps package.json

nanobus maintainers:
Quick and easy fix is to change package.json `"remove-array-items": "^1.0.0"` to `"remove-array-items": "1.0.0"`

**Comment by mreinstein** [comment]
Instead of just routing around the problem, it would help everyone if we fix the upstream issue. pull requests welcome on https://github.com/mreinstein/remove-array-item

**Comment by mreinstein** [comment]
fixed in npm version 1.1.1

**Comment by goto-bus-stop** [comment]
thanks for the fix!
